version: "3.7"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: 'FoodService'              # name of database
      MYSQL_USER: 'FoodService'                # sample is the name of user
      MYSQL_PASSWORD: 'Si@010101'          # password for sample user
      MYSQL_ROOT_PASSWORD: '0101'     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: